
services:
  front-end:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    image: softy-pinko-front-end:task6
    # Removed external port mapping
    depends_on:
      - back-end  # Internal port mapping (for inter-service communication)

  back-end:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    image: softy-pinko-back-end:task6
    # Removed external port mapping

  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    image: softy-pinko-proxy:task6
    ports:
      - "80:80"  # Expose port 80 on the host
    depends_on:
      - front-end
      - back-end
